spring.application.name=backend
gemini.api.key=${GEMINI_API_KEY}
guardian.api.key=${GUARDIAN_API_KEY}

spring.datasource.url=jdbc:postgresql://ep-rough-unit-ao32a392.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

jwt.secret=${JWT_SECRET}
jwt.expiration-ms=86400000